/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadBookIdPositionRouteImport } from './routes/read.$bookId.$position'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdPositionRoute = ReadBookIdPositionRouteImport.update({
  id: '/read/$bookId/$position',
  path: '/read/$bookId/$position',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/read/$bookId/$position': typeof ReadBookIdPositionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/read/$bookId/$position': typeof ReadBookIdPositionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/read/$bookId/$position': typeof ReadBookIdPositionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/read/$bookId/$position'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/read/$bookId/$position'
  id: '__root__' | '/' | '/read/$bookId/$position'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadBookIdPositionRoute: typeof ReadBookIdPositionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId/$position': {
      id: '/read/$bookId/$position'
      path: '/read/$bookId/$position'
      fullPath: '/read/$bookId/$position'
      preLoaderRoute: typeof ReadBookIdPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadBookIdPositionRoute: ReadBookIdPositionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
